### ISSUE TITLE
Too many matches for given filters

### ISSUE THREAD

**Issue by komikat** [OSDG-IIITH/Review-IIIT#12]
Any reason why this is a thing? 
Kinda wanted to take a look at every review and then manually filter by courses I am familiar with :P
https://github.com/OSDG-IIITH/Review-IIIT/blob/794da2bebfebb3bc3ec1237c2177f5649d68404e/frontend/src/pages/Courses.jsx#L173

**Comment by ankith26** [comment]
The only reason its a thing is because trying to view too many courses at once would spam the backend with fetch requests and there are concerns of the backend being unable to handle the increased load due to it, especially with multiple users trying it at around the same time.

It is just a band-aid solution, more-long term solutions I can think of are:
- pagination of the reviews to limit the reviews per page, and therefore limit the number of simultaneous backend fetches
- collapsible review boxes (that are collapsed by default) that require user interaction to fetch reviews.

**Comment by komikat** [comment]
2nd seems fine, users fetch the metadata when filtering and then open up the relevant reviews individually. maybe cache reviews + metadata? personally love [react query](https://www.npmjs.com/package/react-query), almost always a drop in replacement.

**Comment by ankith26** [comment]
The collapsible reviews feature has been implemented, and the too many matches restriction has been lifted. I believe this issue is now resolved, so I am closing this issue.

Feel free to re-open if you have anything to add.
